#!/usr/bin/env bash
# Derive a per-user "flavor" profile for recipes from the local git history,
# and print it as a profile.sh fragment. Read-only — prints to stdout, never
# writes. Redirect to install:
#
#   mkdir -p ~/.local/share/delegate-local
#   bash scripts/derive-flavor.sh > ~/.local/share/delegate-local/profile.sh
#
# The "analyse my own corpus" step of ADR 0013: delegate.sh exposes each
# FLAVOR_* value as a {{flavor_*}} recipe placeholder. Re-run to refresh.
#
# Usage: derive-flavor.sh [--ref <git-ref>] [--count N]
#   --ref    git ref to read history from (default: main, falls back to HEAD)
#   --count  how many recent non-merge commits to sample (default: 200)
set -euo pipefail

ref="main"
count=200
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref) ref="${2:?--ref requires a value}"; shift 2;;
    --count) count="${2:?--count requires a value}"; shift 2;;
    -h|--help) grep '^#' "$0" | sed 's/^#\{1,2\} \{0,1\}//'; exit 0;;
    *) echo "derive-flavor: unknown arg '$1'" >&2; exit 2;;
  esac
done

command -v git >/dev/null 2>&1 || { echo "git not on PATH" >&2; exit 1; }
git rev-parse --git-dir >/dev/null 2>&1 || { echo "not in a git repository" >&2; exit 1; }
# HEAD when the named ref does not exist (fresh clone, detached, other default).
git rev-parse --verify -q "$ref" >/dev/null 2>&1 || ref="HEAD"

# The GitHub squash "(#NN)" suffix is appended by the merge, not authored, so
# it must not skew the length norm or leak into the type parse.
subjects=$(git log "$ref" --no-merges --pretty=format:'%s' -"$count" | sed -E 's/ \(#[0-9]+\)$//')
[[ -n "$subjects" ]] || { echo "no commits found on $ref" >&2; exit 1; }
n=$(printf '%s\n' "$subjects" | grep -c .)

# The 90th-percentile authored length: what the user tolerates beats an
# abstract 50/72 convention.
subject_max=$(printf '%s\n' "$subjects" | awk '{print length}' | sort -n \
  | awk '{a[NR]=$1} END{ i=int(NR*0.9); if (i<1) i=1; print a[i] }')

# Type vocabulary by frequency, comma-joined to match the recipe's allowed-type
# list. A type must appear at least twice, which drops one-off typos.
types=$(printf '%s\n' "$subjects" | sed -nE 's/^([a-z]+)(\([^)]*\))?:.*/\1/p' \
  | sort | uniq -c | sort -rn | awk '$1>=2{printf "%s, ", $2}' | sed 's/, *$//')

printf '# delegate-local flavor profile — generated by scripts/derive-flavor.sh\n'
printf '# Source corpus: %s non-merge commits on %s. Re-run to refresh, or edit to taste.\n' "$n" "$ref"
# An empty value is omitted rather than written: FLAVOR_COMMIT_TYPES="" would
# override the shipped default with an empty list.
[[ -n "$subject_max" ]] && printf 'FLAVOR_COMMIT_SUBJECT_MAX=%s\n' "$subject_max"
[[ -n "$types" ]] && printf 'FLAVOR_COMMIT_TYPES="%s"\n' "$types"
